title: pro-spins.com
subtitle: probing spin-polarized initial states through chiral organic molecules
email:
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pro-spins.com" # the base hostname & protocol for your site, e.g. http://example.com


minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
#permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
logo: "/assets/images/Kolibri.png"
baseurl: ""
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"


defaults:
  - scope:
      path: ""
    values:
      sidebar:
        - title: "Nächstes Treffen"
          text: 9\. Oktober, 16:45 Uhr, auf dem Campus vor der Mensa
        - title: "Veranstaltungen"
          text: >
            **4. September, 12:00 Uhr, Ernst-Abbe-Platz**\\

            <a href="/2024/08/17/aktive-mittagspause.html">Aktive Mittagspause</a>
  - scope:
      path: ""
      type: posts
    values:
      layout: single
  - scope:
      path: ""
      type: pages
    values:
      layout: single


#category_archive:
#  type: liquid
#  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tags/
